#define CONFIG_CCSECURITY_MAX_AUDIT_LOG    1024
#define CONFIG_CCSECURITY_MAX_ACCEPT_ENTRY 2048
//#define CONFIG_CCSECURITY_OMIT_USERSPACE_LOADER
#define CONFIG_CCSECURITY_POLICY_LOADER "/sbin/ccs-init"
#define CONFIG_CCSECURITY_ACTIVATION_TRIGGER "/sbin/init"
//#define CONFIG_AKARI_DEBUG
